defaultMinusAccount: Assets:FIXME
defaultPlusAccount: Expenses:FIXME
defaultCommissionAccount: Expenses:Commission:FIXME
defaultCurrency: CNY
cmb:
  ignoreItem: 财付通
  rules:
    - method: 6214********xxx3
      methodAccount: Assets:CMBXXX3